import { describe, it, expect, vi } from 'vitest';
import worker from './worker.ts';
import { hello } from '../../src/spokenLines.ts';
import { requestOrigin } from '../requestOrigin.ts';
const origin = 'https://roaminglulu.example';
function setup() { return { RURU_SITE_ORIGIN: origin, ASSETS: {fetch: vi.fn(async () => new Response('asset'))} } as any; }
function req(path:string, method='GET', body?:unknown, extra:Record<string,string>={}) {return new Request(origin+path, {method, headers:{'oai-authenticated-user-id':'synthetic-owner', ...(method==='POST'?{'origin':origin,'content-type':'application/json'}:{}),...extra}, ...(body===undefined?{}:{body:JSON.stringify(body)})});}
describe('Sites request adapter',()=>{
 it('serves assets without entering provider routes',async()=>{const env=setup();expect(await (await worker.fetch(req('/'),env)).text()).toBe('asset');expect(env.ASSETS.fetch).toHaveBeenCalledOnce();});
 it('allows public status without Sites login while preserving origin checks',async()=>{const env=setup();expect((await worker.fetch(new Request(origin+'/api/lulu/conversation/status'),env)).status).toBe(200);expect((await worker.fetch(new Request(origin+'/api/lulu/conversation/status',{headers:{origin:'https://other.example'}}),env)).status).toBe(403);});
 it('rejects cross-origin writes',async()=>{expect((await worker.fetch(req('/api/lulu/conversation','POST',{}, {origin:'https://other.example'}),setup())).status).toBe(403);});
 it('rejects cross-site reads even when Origin is absent',async()=>{expect((await worker.fetch(req('/api/lulu/conversation/status','GET',undefined,{'sec-fetch-site':'cross-site'}),setup())).status).toBe(403);});
 it('preserves existing conversation capability response',async()=>{const env=setup();env.OPENAI_API_KEY='synthetic';env.OPENAI_MODEL='test';const res=await worker.fetch(req('/api/lulu/conversation/status'),env);expect(res.status).toBe(200);expect(await res.json()).toEqual({mode:'live'});});
 it('propagates validation error status instead of 200',async()=>{const res=await worker.fetch(req('/api/lulu/conversation','POST',{}),setup());expect(res.status).toBe(400);expect(await res.json()).toHaveProperty('error');});
 it('enforces body limits before provider code',async()=>{const res=await worker.fetch(req('/api/lulu/conversation','POST',{message:'x'.repeat(570001)}),setup());expect(res.status).toBe(413);});
 it('returns empty memory without reading a database',async()=>{const env=setup();env.MEMORY_SESSION_SECRET='synthetic-memory-secret';env.CONVEX_DEPLOY_KEY='synthetic';env.CONVEX_URL='https://famous-tapir-87.convex.cloud';const res=await worker.fetch(req('/api/lulu/memory'),env);expect(res.status).toBe(200);expect(await res.json()).toEqual({state:'empty',version:0});});
 it('mints Secure HttpOnly session cookies only after explicit choice',async()=>{const env=setup();env.MEMORY_SESSION_SECRET='synthetic-memory-secret';env.CONVEX_DEPLOY_KEY='synthetic';env.CONVEX_URL='https://famous-tapir-87.convex.cloud';const denied=await worker.fetch(req('/api/lulu/memory/session','POST',{purpose:'newsletter'}),env);expect(denied.status).toBe(400);expect(denied.headers.has('set-cookie')).toBe(false);const res=await worker.fetch(req('/api/lulu/memory/session','POST',{purpose:'newsletter',consent:true}),env);expect(res.status).toBe(200);expect(res.headers.get('set-cookie')).toContain('HttpOnly; SameSite=Strict; Secure');});
 it('propagates client cancellation to an active voice provider',async()=>{const env=setup();env.ELEVENLABS_API_KEY='synthetic';env.ELEVENLABS_VOICE_ID='synthetic';let providerSignal:AbortSignal|undefined;let started!:()=>void;const ready=new Promise<void>(resolve=>{started=resolve;});vi.stubGlobal('fetch',vi.fn((_url:unknown,init?:RequestInit)=>new Promise<Response>((_resolve,reject)=>{providerSignal=init?.signal as AbortSignal;started();providerSignal.addEventListener('abort',()=>reject(new DOMException('Aborted','AbortError')),{once:true});})));try{const controller=new AbortController();const request=new Request(origin+'/api/lulu/voice',{method:'POST',headers:{'oai-authenticated-user-id':'synthetic-owner',origin,'content-type':'application/json'},body:JSON.stringify({text:hello}),signal:controller.signal});const pending=worker.fetch(request,env);await ready;controller.abort();const res=await pending;expect(res.status).toBe(499);expect(providerSignal?.aborted).toBe(true);}finally{vi.unstubAllGlobals();}});
 it('stops reading a pending upload when the client disconnects',async()=>{const env=setup();const controller=new AbortController();const body=new ReadableStream<Uint8Array>({start(stream){stream.enqueue(new TextEncoder().encode('{"message":"'));}});const request=new Request(origin+'/api/lulu/conversation',{method:'POST',headers:{'oai-authenticated-user-id':'synthetic-owner',origin,'content-type':'application/json'},body,signal:controller.signal,duplex:'half'} as RequestInit);const pending=worker.fetch(request,env);await Promise.resolve();controller.abort();expect((await pending).status).toBe(499);});
 it('propagates outfit cancellation without returning a stale provider error',async()=>{const env=setup();env.FIRECRAWL_API_KEY='synthetic';env.MEMORY_SESSION_SECRET='synthetic';let providerSignal:AbortSignal|undefined;let started!:()=>void;const ready=new Promise<void>(resolve=>{started=resolve;});vi.stubGlobal('fetch',vi.fn((_url:unknown,init?:RequestInit)=>new Promise<Response>((_resolve,reject)=>{providerSignal=init?.signal as AbortSignal;started();providerSignal.addEventListener('abort',()=>reject(new DOMException('Aborted','AbortError')),{once:true});})));try{const controller=new AbortController();const request=new Request(origin+'/api/lulu/outfit/suggest',{method:'POST',headers:{'oai-authenticated-user-id':'synthetic-owner',origin,'content-type':'application/json'},body:JSON.stringify({garment:'jacket',color:'blue',style:'casual',interest:'exploring'}),signal:controller.signal});const pending=worker.fetch(request,env);await ready;controller.abort();const res=await pending;expect(res.status).toBe(499);expect(providerSignal?.aborted).toBe(true);}finally{vi.unstubAllGlobals();}});
 it('accepts only exact configured HTTPS origins or loopback rehearsal hosts',()=>{expect(requestOrigin({headers:{host:'roaminglulu.example'}} as any,{RURU_SITE_ORIGIN:origin})).toBe(origin);expect(requestOrigin({headers:{host:'other.example'}} as any,{RURU_SITE_ORIGIN:origin})).toBeNull();expect(requestOrigin({headers:{host:'roaminglulu.example'}} as any,{RURU_SITE_ORIGIN:'http://roaminglulu.example'})).toBeNull();expect(requestOrigin({headers:{host:'localhost:4317'}} as any,{})).toBe('http://localhost:4317');expect(requestOrigin({headers:{host:'localhost.example:4317'}} as any,{})).toBeNull();});
});
